spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university
    username: postgres
    password: admin
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
security:
  logins: admin,user
  passwords: admin,password
  roles: ADMIN,USER